name: cache-test

on:
  workflow_dispatch:

jobs:
  run_cache:
    strategy:
      fail-fast: false
      matrix:
        vc_boost:
          - name: msvc-2019_boost_1730
            image: 'windows-2019'
            boost_url: 'https://boostorg.jfrog.io/artifactory/main/release/1.73.0/source/boost_1_73_0.tar.gz'
            boost_archive_name: 'boost_1_73_0.tar.gz'
            boost_folder_name: 'boost_1_73_0'
            boost_include_folder: 'C:\Boost\include\boost-1_73'
        arch:
          - cmake: Win32
            choco_options: '--x86'
            address_model: 32
        build_type:
          - Debug
        shared_libs:
          - toggle: OFF
            name: Static
        with_openssl:
          - toggle: OFF
            name: 'noSSL'

    runs-on: ${{ matrix.vc_boost.image }}
    env:
      JOB_NAME: Windows_(${{ matrix.vc_boost.name }},${{ matrix.arch.address_model }},${{ matrix.build_type }},${{ matrix.shared_libs.name }}, ${{ matrix.with_openssl.name }})
    name: >-
      Windows
      (${{ matrix.vc_boost.name }}, ${{ matrix.arch.address_model }}, ${{ matrix.build_type }}, ${{ matrix.shared_libs.name }}, ${{ matrix.with_openssl.name }})

    steps:
      - uses: actions/checkout@v2

      - name: Install Boost
        run: |
          Invoke-WebRequest `
              "${{ matrix.vc_boost.boost_url }}" `
              -OutFile "${{ matrix.vc_boost.boost_archive_name }}" `
              -UserAgent "''"
          tar xzf ${{ matrix.vc_boost.boost_archive_name }}
          rm ${{ matrix.vc_boost.boost_archive_name }}
          cd ${{ matrix.vc_boost.boost_folder_name }}
          .\bootstrap.bat
          .\b2 address-model=${{ matrix.arch.address_model }} --with-atomic --with-thread --with-chrono install
          cd ..
          Remove-Item ${{ matrix.vc_boost.boost_folder_name }} -Recurse -Force

   
